// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using byr.IDP.DbContexts;

#nullable disable

namespace byr.IDP.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.20");

            modelBuilder.Entity("byr.IDP.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Subject")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("13229d33-99e0-41b3-b18d-4f72127e3971"),
                            Active = true,
                            ConcurrencyStamp = "5765e02a-eb14-451d-8924-a0d4eff1e7d4",
                            Password = "password",
                            Subject = "d860efca-22d9-47fd-8249-791ba61b07c7",
                            UserName = "David"
                        },
                        new
                        {
                            Id = new Guid("96053525-f4a5-47ee-855e-0ea77fa6c55a"),
                            Active = true,
                            ConcurrencyStamp = "e81cd01e-5501-4097-9954-0d6e0d482be0",
                            Password = "password",
                            Subject = "b7539694-97e7-4dfe-84da-b4256e1ff5c7",
                            UserName = "Emma"
                        },
                        new
                        {
                            Id = new Guid("ca48eb08-46f0-493b-aad6-ce567205e507"),
                            Active = true,
                            ConcurrencyStamp = "27fe4c87-932a-4e2c-a748-aa79701a28f0",
                            Password = "password",
                            Subject = "1Subject",
                            UserName = "Alice"
                        });
                });

            modelBuilder.Entity("byr.IDP.Entities.UserClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3754058e-ead5-44f7-b114-e8ae8d272a66"),
                            ConcurrencyStamp = "71d2bd9a-3aad-4c04-8ec1-87888ef4081f",
                            Type = "given_name",
                            UserId = new Guid("13229d33-99e0-41b3-b18d-4f72127e3971"),
                            Value = "David"
                        },
                        new
                        {
                            Id = new Guid("ae6ad9a6-0fc3-4d60-98c7-2d5eb8a6836c"),
                            ConcurrencyStamp = "4c5e61ea-824f-4030-97a0-f247b12bf6e4",
                            Type = "family_name",
                            UserId = new Guid("13229d33-99e0-41b3-b18d-4f72127e3971"),
                            Value = "Flagg"
                        },
                        new
                        {
                            Id = new Guid("21dbbf8d-a91d-4afc-a540-c3f6d9e7fd67"),
                            ConcurrencyStamp = "256992a9-cb26-411d-b14a-138fde9a57c7",
                            Type = "country",
                            UserId = new Guid("13229d33-99e0-41b3-b18d-4f72127e3971"),
                            Value = "nl"
                        },
                        new
                        {
                            Id = new Guid("b67036af-1545-49cd-b203-cc59f5d44b72"),
                            ConcurrencyStamp = "febed8be-fec4-460d-8ec7-a3e996cb9421",
                            Type = "role",
                            UserId = new Guid("13229d33-99e0-41b3-b18d-4f72127e3971"),
                            Value = "FreeUser"
                        },
                        new
                        {
                            Id = new Guid("efb0d6f3-0efc-4eea-8b7e-00759af5460a"),
                            ConcurrencyStamp = "d484e793-c7b1-4761-be54-9083036b5dd3",
                            Type = "given_name",
                            UserId = new Guid("96053525-f4a5-47ee-855e-0ea77fa6c55a"),
                            Value = "Emma"
                        },
                        new
                        {
                            Id = new Guid("5b93682a-e2e4-4b4c-b76c-22b1fa5dad55"),
                            ConcurrencyStamp = "c52867f6-0ec1-4161-8900-9320e8e6d0c0",
                            Type = "family_name",
                            UserId = new Guid("96053525-f4a5-47ee-855e-0ea77fa6c55a"),
                            Value = "Flagg"
                        },
                        new
                        {
                            Id = new Guid("a76bd531-138e-4d3f-9474-802947e96bee"),
                            ConcurrencyStamp = "5dbf80eb-35c5-4a6e-b3da-43c52946534b",
                            Type = "country",
                            UserId = new Guid("96053525-f4a5-47ee-855e-0ea77fa6c55a"),
                            Value = "be"
                        },
                        new
                        {
                            Id = new Guid("dbeb5c70-66f2-44ea-9a3a-e8962fd6b167"),
                            ConcurrencyStamp = "d0e1ce0f-3aa9-437e-9dc9-84e0e5670f1f",
                            Type = "role",
                            UserId = new Guid("96053525-f4a5-47ee-855e-0ea77fa6c55a"),
                            Value = "PayingUser"
                        },
                        new
                        {
                            Id = new Guid("33b16eb8-3f56-4c20-abe7-2e5e2a95e7e8"),
                            ConcurrencyStamp = "3482a805-0975-42f2-80e7-8fc6fc957767",
                            Type = "given_name",
                            UserId = new Guid("ca48eb08-46f0-493b-aad6-ce567205e507"),
                            Value = "Alice"
                        },
                        new
                        {
                            Id = new Guid("1a17d296-4f4f-4159-960c-fa4e7c72246d"),
                            ConcurrencyStamp = "5fa3442c-11d5-47e7-880f-eac0cf06cd43",
                            Type = "family_name",
                            UserId = new Guid("ca48eb08-46f0-493b-aad6-ce567205e507"),
                            Value = "Smith"
                        },
                        new
                        {
                            Id = new Guid("c9ed2dd8-047e-4427-90c5-3c77942175ae"),
                            ConcurrencyStamp = "47756fa7-1acc-45b7-a37f-57aad0b36f62",
                            Type = "country",
                            UserId = new Guid("ca48eb08-46f0-493b-aad6-ce567205e507"),
                            Value = "be"
                        },
                        new
                        {
                            Id = new Guid("83148847-bb4e-4227-8137-b4887d119ef2"),
                            ConcurrencyStamp = "54b1e6d4-770e-4177-9307-f33231023786",
                            Type = "role",
                            UserId = new Guid("ca48eb08-46f0-493b-aad6-ce567205e507"),
                            Value = "PayingUser"
                        });
                });

            modelBuilder.Entity("byr.IDP.Entities.UserClaim", b =>
                {
                    b.HasOne("byr.IDP.Entities.User", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("byr.IDP.Entities.User", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
